services:
  - type: web
    name: langflow-oauth
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: UPSTREAM
        fromService:
          name: Langflow
          type: pserv
          property: hostport
      - key: OAUTH2_PROXY_PROVIDER
        sync: false
      - key: OAUTH2_PROXY_CLIENT_ID
        sync: false
      - key: OAUTH2_PROXY_CLIENT_SECRET
        sync: false
      - key: OAUTH2_PROXY_COOKIE_SECRET
        generateValue: true
      - key: OAUTH2_PROXY_EMAIL_DOMAINS
        value: '*'
      - key: OAUTH2_PROXY_HTTP_ADDRESS
        value: ":10000"
      - key: OAUTH2_PROXY_LOGIN_URL_PARAMETERS
        sync: false
